; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

[core_settings]
upload_speed = 115200		;ESP8266 74880, ESP32 115200
monitor_speed = 115200

[env]
framework = arduino
; automatically inherit attributes from core_settings
extends = core_settings
; make some settings visible as macros
; string-escape string values, integers are passed as normal
build_flags =
	-fexceptions
;	-D ARDUINO_USB_MODE=0
;	-D ARDUINO_USB_CDC_ON_BOOT=1
  -D MONITOR_SPEED=${core_settings.monitor_speed}
lib_deps =
	symlink://../include/credentials
	symlink://../mqtt_wifi/lib/mqtt_wifi_ota
	hideakitai/MQTTPubSubClient @ ^0.3.2

[env:esp32]
board = esp32-s2-saola-1
;board = esp32doit-devkit-v1
;board = lolin_s2_mini
;upload_port = COM17
;monitor_port = COM18
platform = espressif32	;@6.5.0

[env:esp8266]
board = esp07
;board = nodemcuv2
;board = d1_mini
platform = espressif8266
board_build.flash_mode = dout
